name = "odbc"
version = "1.0.0"
maintainer = "David Pfister"
author = "David Pfister"
description = "odbc wrapper for modern Fortran"
categories = ["odbc"]
keywords = ["odbc", "swig", "sql", "database"]
homepage = "https://github.com/davidpfister/odbc.f"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = "odbc32"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM", "_WIN32"]

[library]
source-dir = "src"

[install]
library = false

[[test]]
name = "test"
source-dir = "tests"
