/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 


/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif



#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(PTR)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }



#define SWIG_VERSION 0x040200
#define SWIGFORTRAN

#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 

                // This adds the include to the generated wrapper.
#include <sql.h>

SWIGEXPORT int _wrap_SQL_NULL_DATA_get() {
  int fresult ;
  int result;
  
  result = (int)((-1));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DATA_AT_EXEC_get() {
  int fresult ;
  int result;
  
  result = (int)((-2));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SUCCESS_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SUCCESS_WITH_INFO_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NO_DATA_get() {
  int fresult ;
  int result;
  
  result = (int)(100);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ERROR_get() {
  int fresult ;
  int result;
  
  result = (int)((-1));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INVALID_HANDLE_get() {
  int fresult ;
  int result;
  
  result = (int)((-2));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_STILL_EXECUTING_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NEED_DATA_get() {
  int fresult ;
  int result;
  
  result = (int)(99);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_PARAM_DATA_AVAILABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(101);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NTS_get() {
  int fresult ;
  int result;
  
  result = (int)((-3));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_NTSL_get() {
  long fresult ;
  long result;
  
  result = (long)((-3L));
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_MESSAGE_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(512);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DATE_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(10);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TIME_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TIMESTAMP_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(19);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_OUTPUT_NTS_get() {
  int fresult ;
  int result;
  
  result = (int)(10001);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_AUTO_IPD_get() {
  int fresult ;
  int result;
  
  result = (int)(10001);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_METADATA_ID_get() {
  int fresult ;
  int result;
  
  result = (int)(10014);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_APP_ROW_DESC_get() {
  int fresult ;
  int result;
  
  result = (int)(10010);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_APP_PARAM_DESC_get() {
  int fresult ;
  int result;
  
  result = (int)(10011);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_IMP_ROW_DESC_get() {
  int fresult ;
  int result;
  
  result = (int)(10012);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_IMP_PARAM_DESC_get() {
  int fresult ;
  int result;
  
  result = (int)(10013);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_CURSOR_SCROLLABLE_get() {
  int fresult ;
  int result;
  
  result = (int)((-1));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ATTR_CURSOR_SENSITIVITY_get() {
  int fresult ;
  int result;
  
  result = (int)((-2));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NONSCROLLABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SCROLLABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_COUNT_get() {
  int fresult ;
  int result;
  
  result = (int)(1001);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_TYPE_get() {
  int fresult ;
  int result;
  
  result = (int)(1002);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(1003);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_OCTET_LENGTH_PTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1004);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_PRECISION_get() {
  int fresult ;
  int result;
  
  result = (int)(1005);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_SCALE_get() {
  int fresult ;
  int result;
  
  result = (int)(1006);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_DATETIME_INTERVAL_CODE_get() {
  int fresult ;
  int result;
  
  result = (int)(1007);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_NULLABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(1008);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_INDICATOR_PTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1009);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_DATA_PTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1010);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(1011);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_UNNAMED_get() {
  int fresult ;
  int result;
  
  result = (int)(1012);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_OCTET_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(1013);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_ALLOC_TYPE_get() {
  int fresult ;
  int result;
  
  result = (int)(1099);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_RETURNCODE_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_NUMBER_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_ROW_COUNT_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_SQLSTATE_get() {
  int fresult ;
  int result;
  
  result = (int)(4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_NATIVE_get() {
  int fresult ;
  int result;
  
  result = (int)(5);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_MESSAGE_TEXT_get() {
  int fresult ;
  int result;
  
  result = (int)(6);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DYNAMIC_FUNCTION_get() {
  int fresult ;
  int result;
  
  result = (int)(7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CLASS_ORIGIN_get() {
  int fresult ;
  int result;
  
  result = (int)(8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_SUBCLASS_ORIGIN_get() {
  int fresult ;
  int result;
  
  result = (int)(9);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CONNECTION_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(10);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_SERVER_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(11);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DYNAMIC_FUNCTION_CODE_get() {
  int fresult ;
  int result;
  
  result = (int)(12);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_ALTER_DOMAIN_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_ALTER_TABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CALL_get() {
  int fresult ;
  int result;
  
  result = (int)(7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_ASSERTION_get() {
  int fresult ;
  int result;
  
  result = (int)(6);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_CHARACTER_SET_get() {
  int fresult ;
  int result;
  
  result = (int)(8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_COLLATION_get() {
  int fresult ;
  int result;
  
  result = (int)(10);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_DOMAIN_get() {
  int fresult ;
  int result;
  
  result = (int)(23);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_INDEX_get() {
  int fresult ;
  int result;
  
  result = (int)((-1));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_SCHEMA_get() {
  int fresult ;
  int result;
  
  result = (int)(64);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_TABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(77);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_TRANSLATION_get() {
  int fresult ;
  int result;
  
  result = (int)(79);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_CREATE_VIEW_get() {
  int fresult ;
  int result;
  
  result = (int)(84);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DELETE_WHERE_get() {
  int fresult ;
  int result;
  
  result = (int)(19);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_ASSERTION_get() {
  int fresult ;
  int result;
  
  result = (int)(24);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_CHARACTER_SET_get() {
  int fresult ;
  int result;
  
  result = (int)(25);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_COLLATION_get() {
  int fresult ;
  int result;
  
  result = (int)(26);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_DOMAIN_get() {
  int fresult ;
  int result;
  
  result = (int)(27);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_INDEX_get() {
  int fresult ;
  int result;
  
  result = (int)((-2));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_SCHEMA_get() {
  int fresult ;
  int result;
  
  result = (int)(31);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_TABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(32);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_TRANSLATION_get() {
  int fresult ;
  int result;
  
  result = (int)(33);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DROP_VIEW_get() {
  int fresult ;
  int result;
  
  result = (int)(36);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DYNAMIC_DELETE_CURSOR_get() {
  int fresult ;
  int result;
  
  result = (int)(38);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_DYNAMIC_UPDATE_CURSOR_get() {
  int fresult ;
  int result;
  
  result = (int)(81);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_GRANT_get() {
  int fresult ;
  int result;
  
  result = (int)(48);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_INSERT_get() {
  int fresult ;
  int result;
  
  result = (int)(50);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_REVOKE_get() {
  int fresult ;
  int result;
  
  result = (int)(59);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_SELECT_CURSOR_get() {
  int fresult ;
  int result;
  
  result = (int)(85);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_UNKNOWN_STATEMENT_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DIAG_UPDATE_WHERE_get() {
  int fresult ;
  int result;
  
  result = (int)(82);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_UNKNOWN_TYPE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CHAR_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NUMERIC_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DECIMAL_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INTEGER_get() {
  int fresult ;
  int result;
  
  result = (int)(4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SMALLINT_get() {
  int fresult ;
  int result;
  
  result = (int)(5);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FLOAT_get() {
  int fresult ;
  int result;
  
  result = (int)(6);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_REAL_get() {
  int fresult ;
  int result;
  
  result = (int)(7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DOUBLE_get() {
  int fresult ;
  int result;
  
  result = (int)(8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DATETIME_get() {
  int fresult ;
  int result;
  
  result = (int)(9);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_VARCHAR_get() {
  int fresult ;
  int result;
  
  result = (int)(12);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TYPE_DATE_get() {
  int fresult ;
  int result;
  
  result = (int)(91);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TYPE_TIME_get() {
  int fresult ;
  int result;
  
  result = (int)(92);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TYPE_TIMESTAMP_get() {
  int fresult ;
  int result;
  
  result = (int)(93);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_UNSPECIFIED_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INSENSITIVE_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SENSITIVE_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ALL_TYPES_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DEFAULT_get() {
  int fresult ;
  int result;
  
  result = (int)(99);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ARD_TYPE_get() {
  int fresult ;
  int result;
  
  result = (int)((-99));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CODE_DATE_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CODE_TIME_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CODE_TIMESTAMP_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FALSE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TRUE_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NO_NULLS_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULLABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULLABLE_UNKNOWN_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_PRED_NONE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_PRED_CHAR_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_PRED_BASIC_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NAMED_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_UNNAMED_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_ALLOC_AUTO_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESC_ALLOC_USER_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CLOSE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DROP_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_UNBIND_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_RESET_PARAMS_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FETCH_NEXT_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FETCH_FIRST_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FETCH_LAST_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FETCH_PRIOR_get() {
  int fresult ;
  int result;
  
  result = (int)(4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FETCH_ABSOLUTE_get() {
  int fresult ;
  int result;
  
  result = (int)(5);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FETCH_RELATIVE_get() {
  int fresult ;
  int result;
  
  result = (int)(6);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_COMMIT_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ROLLBACK_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULL_HENV_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULL_HDBC_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULL_HSTMT_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULL_HDESC_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULL_DESC_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_NULL_HANDLE_get() {
  long fresult ;
  long result;
  
  result = (long)(0L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SCOPE_CURROW_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SCOPE_TRANSACTION_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SCOPE_SESSION_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_PC_UNKNOWN_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_PC_NON_PSEUDO_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_PC_PSEUDO_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ROW_IDENTIFIER_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INDEX_UNIQUE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INDEX_ALL_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INDEX_CLUSTERED_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INDEX_HASHED_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INDEX_OTHER_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLALLOCCONNECT_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLALLOCENV_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLALLOCHANDLE_get() {
  int fresult ;
  int result;
  
  result = (int)(1001);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLALLOCSTMT_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLBINDCOL_get() {
  int fresult ;
  int result;
  
  result = (int)(4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLBINDPARAM_get() {
  int fresult ;
  int result;
  
  result = (int)(1002);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLCANCEL_get() {
  int fresult ;
  int result;
  
  result = (int)(5);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLCLOSECURSOR_get() {
  int fresult ;
  int result;
  
  result = (int)(1003);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLCOLATTRIBUTE_get() {
  int fresult ;
  int result;
  
  result = (int)(6);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLCOLUMNS_get() {
  int fresult ;
  int result;
  
  result = (int)(40);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLCONNECT_get() {
  int fresult ;
  int result;
  
  result = (int)(7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLCOPYDESC_get() {
  int fresult ;
  int result;
  
  result = (int)(1004);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLDATASOURCES_get() {
  int fresult ;
  int result;
  
  result = (int)(57);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLDESCRIBECOL_get() {
  int fresult ;
  int result;
  
  result = (int)(8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLDISCONNECT_get() {
  int fresult ;
  int result;
  
  result = (int)(9);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLENDTRAN_get() {
  int fresult ;
  int result;
  
  result = (int)(1005);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLERROR_get() {
  int fresult ;
  int result;
  
  result = (int)(10);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLEXECDIRECT_get() {
  int fresult ;
  int result;
  
  result = (int)(11);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLEXECUTE_get() {
  int fresult ;
  int result;
  
  result = (int)(12);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLFETCH_get() {
  int fresult ;
  int result;
  
  result = (int)(13);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLFETCHSCROLL_get() {
  int fresult ;
  int result;
  
  result = (int)(1021);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLFREECONNECT_get() {
  int fresult ;
  int result;
  
  result = (int)(14);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLFREEENV_get() {
  int fresult ;
  int result;
  
  result = (int)(15);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLFREEHANDLE_get() {
  int fresult ;
  int result;
  
  result = (int)(1006);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLFREESTMT_get() {
  int fresult ;
  int result;
  
  result = (int)(16);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETCONNECTATTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1007);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETCONNECTOPTION_get() {
  int fresult ;
  int result;
  
  result = (int)(42);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETCURSORNAME_get() {
  int fresult ;
  int result;
  
  result = (int)(17);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETDATA_get() {
  int fresult ;
  int result;
  
  result = (int)(43);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETDESCFIELD_get() {
  int fresult ;
  int result;
  
  result = (int)(1008);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETDESCREC_get() {
  int fresult ;
  int result;
  
  result = (int)(1009);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETDIAGFIELD_get() {
  int fresult ;
  int result;
  
  result = (int)(1010);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETDIAGREC_get() {
  int fresult ;
  int result;
  
  result = (int)(1011);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETENVATTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1012);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETFUNCTIONS_get() {
  int fresult ;
  int result;
  
  result = (int)(44);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETINFO_get() {
  int fresult ;
  int result;
  
  result = (int)(45);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETSTMTATTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1014);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETSTMTOPTION_get() {
  int fresult ;
  int result;
  
  result = (int)(46);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLGETTYPEINFO_get() {
  int fresult ;
  int result;
  
  result = (int)(47);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLNUMRESULTCOLS_get() {
  int fresult ;
  int result;
  
  result = (int)(18);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLPARAMDATA_get() {
  int fresult ;
  int result;
  
  result = (int)(48);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLPREPARE_get() {
  int fresult ;
  int result;
  
  result = (int)(19);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLPUTDATA_get() {
  int fresult ;
  int result;
  
  result = (int)(49);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLROWCOUNT_get() {
  int fresult ;
  int result;
  
  result = (int)(20);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETCONNECTATTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1016);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETCONNECTOPTION_get() {
  int fresult ;
  int result;
  
  result = (int)(50);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETCURSORNAME_get() {
  int fresult ;
  int result;
  
  result = (int)(21);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETDESCFIELD_get() {
  int fresult ;
  int result;
  
  result = (int)(1017);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETDESCREC_get() {
  int fresult ;
  int result;
  
  result = (int)(1018);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETENVATTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1019);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETPARAM_get() {
  int fresult ;
  int result;
  
  result = (int)(22);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETSTMTATTR_get() {
  int fresult ;
  int result;
  
  result = (int)(1020);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSETSTMTOPTION_get() {
  int fresult ;
  int result;
  
  result = (int)(51);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSPECIALCOLUMNS_get() {
  int fresult ;
  int result;
  
  result = (int)(52);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLSTATISTICS_get() {
  int fresult ;
  int result;
  
  result = (int)(53);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLTABLES_get() {
  int fresult ;
  int result;
  
  result = (int)(54);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLTRANSACT_get() {
  int fresult ;
  int result;
  
  result = (int)(23);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_API_SQLCANCELHANDLE_get() {
  int fresult ;
  int result;
  
  result = (int)(1022);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_DRIVER_CONNECTIONS_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_DRIVER_CONNECTIONS_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_CONCURRENT_ACTIVITIES_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_CONCURRENT_ACTIVITIES_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DATA_SOURCE_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_FETCH_DIRECTION_get() {
  int fresult ;
  int result;
  
  result = (int)(8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SERVER_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(13);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SEARCH_PATTERN_ESCAPE_get() {
  int fresult ;
  int result;
  
  result = (int)(14);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DBMS_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(17);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DBMS_VER_get() {
  int fresult ;
  int result;
  
  result = (int)(18);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ACCESSIBLE_TABLES_get() {
  int fresult ;
  int result;
  
  result = (int)(19);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ACCESSIBLE_PROCEDURES_get() {
  int fresult ;
  int result;
  
  result = (int)(20);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CURSOR_COMMIT_BEHAVIOR_get() {
  int fresult ;
  int result;
  
  result = (int)(23);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DATA_SOURCE_READ_ONLY_get() {
  int fresult ;
  int result;
  
  result = (int)(25);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DEFAULT_TXN_ISOLATION_get() {
  int fresult ;
  int result;
  
  result = (int)(26);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_IDENTIFIER_CASE_get() {
  int fresult ;
  int result;
  
  result = (int)(28);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_IDENTIFIER_QUOTE_CHAR_get() {
  int fresult ;
  int result;
  
  result = (int)(29);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_COLUMN_NAME_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(30);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_COLUMN_NAME_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(30);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_CURSOR_NAME_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(31);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_CURSOR_NAME_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(31);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_SCHEMA_NAME_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(32);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_SCHEMA_NAME_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(32);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_CATALOG_NAME_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(34);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_CATALOG_NAME_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(34);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_TABLE_NAME_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(35);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SCROLL_CONCURRENCY_get() {
  int fresult ;
  int result;
  
  result = (int)(43);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TXN_CAPABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(46);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TRANSACTION_CAPABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(46);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_USER_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(47);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TXN_ISOLATION_OPTION_get() {
  int fresult ;
  int result;
  
  result = (int)(72);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TRANSACTION_ISOLATION_OPTION_get() {
  int fresult ;
  int result;
  
  result = (int)(72);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_INTEGRITY_get() {
  int fresult ;
  int result;
  
  result = (int)(73);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_GETDATA_EXTENSIONS_get() {
  int fresult ;
  int result;
  
  result = (int)(81);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NULL_COLLATION_get() {
  int fresult ;
  int result;
  
  result = (int)(85);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ALTER_TABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(86);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_ORDER_BY_COLUMNS_IN_SELECT_get() {
  int fresult ;
  int result;
  
  result = (int)(90);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_SPECIAL_CHARACTERS_get() {
  int fresult ;
  int result;
  
  result = (int)(94);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_COLUMNS_IN_GROUP_BY_get() {
  int fresult ;
  int result;
  
  result = (int)(97);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_COLUMNS_IN_GROUP_BY_get() {
  int fresult ;
  int result;
  
  result = (int)(97);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_COLUMNS_IN_INDEX_get() {
  int fresult ;
  int result;
  
  result = (int)(98);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_COLUMNS_IN_INDEX_get() {
  int fresult ;
  int result;
  
  result = (int)(98);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_COLUMNS_IN_ORDER_BY_get() {
  int fresult ;
  int result;
  
  result = (int)(99);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_COLUMNS_IN_ORDER_BY_get() {
  int fresult ;
  int result;
  
  result = (int)(99);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_COLUMNS_IN_SELECT_get() {
  int fresult ;
  int result;
  
  result = (int)(100);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_COLUMNS_IN_SELECT_get() {
  int fresult ;
  int result;
  
  result = (int)(100);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_COLUMNS_IN_TABLE_get() {
  int fresult ;
  int result;
  
  result = (int)(101);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_INDEX_SIZE_get() {
  int fresult ;
  int result;
  
  result = (int)(102);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_INDEX_SIZE_get() {
  int fresult ;
  int result;
  
  result = (int)(102);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_ROW_SIZE_get() {
  int fresult ;
  int result;
  
  result = (int)(104);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_ROW_SIZE_get() {
  int fresult ;
  int result;
  
  result = (int)(104);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_STATEMENT_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(105);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_STATEMENT_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(105);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_TABLES_IN_SELECT_get() {
  int fresult ;
  int result;
  
  result = (int)(106);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_TABLES_IN_SELECT_get() {
  int fresult ;
  int result;
  
  result = (int)(106);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_USER_NAME_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(107);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_USER_NAME_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(107);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_OJ_CAPABILITIES_get() {
  int fresult ;
  int result;
  
  result = (int)(115);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_OUTER_JOIN_CAPABILITIES_get() {
  int fresult ;
  int result;
  
  result = (int)(115);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_XOPEN_CLI_YEAR_get() {
  int fresult ;
  int result;
  
  result = (int)(10000);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CURSOR_SENSITIVITY_get() {
  int fresult ;
  int result;
  
  result = (int)(10001);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_DESCRIBE_PARAMETER_get() {
  int fresult ;
  int result;
  
  result = (int)(10002);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CATALOG_NAME_get() {
  int fresult ;
  int result;
  
  result = (int)(10003);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_COLLATION_SEQ_get() {
  int fresult ;
  int result;
  
  result = (int)(10004);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_IDENTIFIER_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(10005);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAXIMUM_IDENTIFIER_LENGTH_get() {
  int fresult ;
  int result;
  
  result = (int)(10005);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_AT_ADD_COLUMN_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000001L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_AT_DROP_COLUMN_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000002L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_AT_ADD_CONSTRAINT_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000008L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_AM_NONE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_AM_CONNECTION_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_AM_STATEMENT_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CB_DELETE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CB_CLOSE_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_CB_PRESERVE_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_FD_FETCH_NEXT_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000001L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_FD_FETCH_FIRST_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000002L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_FD_FETCH_LAST_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000004L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_FD_FETCH_PRIOR_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000008L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_FD_FETCH_ABSOLUTE_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000010L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_FD_FETCH_RELATIVE_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000020L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_GD_ANY_COLUMN_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000001L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_GD_ANY_ORDER_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000002L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_IC_UPPER_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_IC_LOWER_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_IC_SENSITIVE_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_IC_MIXED_get() {
  int fresult ;
  int result;
  
  result = (int)(4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_OJ_LEFT_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000001L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_OJ_RIGHT_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000002L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_OJ_FULL_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000004L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_OJ_NESTED_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000008L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_OJ_NOT_ORDERED_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000010L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_OJ_INNER_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000020L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_OJ_ALL_COMPARISON_OPS_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000040L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_SCCO_READ_ONLY_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000001L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_SCCO_LOCK_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000002L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_SCCO_OPT_ROWVER_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000004L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_SCCO_OPT_VALUES_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000008L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TC_NONE_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TC_DML_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TC_ALL_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TC_DDL_COMMIT_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_TC_DDL_IGNORE_get() {
  int fresult ;
  int result;
  
  result = (int)(4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TXN_READ_UNCOMMITTED_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000001L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TRANSACTION_READ_UNCOMMITTED_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000001L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TXN_READ_COMMITTED_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000002L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TRANSACTION_READ_COMMITTED_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000002L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TXN_REPEATABLE_READ_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000004L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TRANSACTION_REPEATABLE_READ_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000004L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TXN_SERIALIZABLE_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000008L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT long _wrap_SQL_TRANSACTION_SERIALIZABLE_get() {
  long fresult ;
  long result;
  
  result = (long)(0x00000008L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NC_HIGH_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_NC_LOW_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}



