! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module sqltypes
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct tagDATE_STRUCT
 type, public :: DATE_STRUCT
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_year => swigf_DATE_STRUCT_year_set
  procedure :: get_year => swigf_DATE_STRUCT_year_get
  procedure :: set_month => swigf_DATE_STRUCT_month_set
  procedure :: get_month => swigf_DATE_STRUCT_month_get
  procedure :: set_day => swigf_DATE_STRUCT_day_set
  procedure :: get_day => swigf_DATE_STRUCT_day_get
  procedure :: release => swigf_DATE_STRUCT_release
  procedure, private :: swigf_DATE_STRUCT_op_assign__
  generic :: assignment(=) => swigf_DATE_STRUCT_op_assign__
 end type DATE_STRUCT
 ! struct struct tagTIME_STRUCT
 type, public :: TIME_STRUCT
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_hour => swigf_TIME_STRUCT_hour_set
  procedure :: get_hour => swigf_TIME_STRUCT_hour_get
  procedure :: set_minute => swigf_TIME_STRUCT_minute_set
  procedure :: get_minute => swigf_TIME_STRUCT_minute_get
  procedure :: set_second => swigf_TIME_STRUCT_second_set
  procedure :: get_second => swigf_TIME_STRUCT_second_get
  procedure :: release => swigf_TIME_STRUCT_release
  procedure, private :: swigf_TIME_STRUCT_op_assign__
  generic :: assignment(=) => swigf_TIME_STRUCT_op_assign__
 end type TIME_STRUCT
 ! struct struct tagTIMESTAMP_STRUCT
 type, public :: TIMESTAMP_STRUCT
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_year => swigf_TIMESTAMP_STRUCT_year_set
  procedure :: get_year => swigf_TIMESTAMP_STRUCT_year_get
  procedure :: set_month => swigf_TIMESTAMP_STRUCT_month_set
  procedure :: get_month => swigf_TIMESTAMP_STRUCT_month_get
  procedure :: set_day => swigf_TIMESTAMP_STRUCT_day_set
  procedure :: get_day => swigf_TIMESTAMP_STRUCT_day_get
  procedure :: set_hour => swigf_TIMESTAMP_STRUCT_hour_set
  procedure :: get_hour => swigf_TIMESTAMP_STRUCT_hour_get
  procedure :: set_minute => swigf_TIMESTAMP_STRUCT_minute_set
  procedure :: get_minute => swigf_TIMESTAMP_STRUCT_minute_get
  procedure :: set_second => swigf_TIMESTAMP_STRUCT_second_set
  procedure :: get_second => swigf_TIMESTAMP_STRUCT_second_get
  procedure :: set_fraction => swigf_TIMESTAMP_STRUCT_fraction_set
  procedure :: get_fraction => swigf_TIMESTAMP_STRUCT_fraction_get
  procedure :: release => swigf_TIMESTAMP_STRUCT_release
  procedure, private :: swigf_TIMESTAMP_STRUCT_op_assign__
  generic :: assignment(=) => swigf_TIMESTAMP_STRUCT_op_assign__
 end type TIMESTAMP_STRUCT
 ! typedef enum SQLINTERVAL
 enum, bind(c)
  enumerator :: SQL_IS_YEAR = 1
  enumerator :: SQL_IS_MONTH = 2
  enumerator :: SQL_IS_DAY = 3
  enumerator :: SQL_IS_HOUR = 4
  enumerator :: SQL_IS_MINUTE = 5
  enumerator :: SQL_IS_SECOND = 6
  enumerator :: SQL_IS_YEAR_TO_MONTH = 7
  enumerator :: SQL_IS_DAY_TO_HOUR = 8
  enumerator :: SQL_IS_DAY_TO_MINUTE = 9
  enumerator :: SQL_IS_DAY_TO_SECOND = 10
  enumerator :: SQL_IS_HOUR_TO_MINUTE = 11
  enumerator :: SQL_IS_HOUR_TO_SECOND = 12
  enumerator :: SQL_IS_MINUTE_TO_SECOND = 13
 end enum
 integer, parameter, public :: SQLINTERVAL = kind(SQL_IS_YEAR)
 public :: SQL_IS_YEAR, SQL_IS_MONTH, SQL_IS_DAY, SQL_IS_HOUR, SQL_IS_MINUTE, SQL_IS_SECOND, SQL_IS_YEAR_TO_MONTH, &
    SQL_IS_DAY_TO_HOUR, SQL_IS_DAY_TO_MINUTE, SQL_IS_DAY_TO_SECOND, SQL_IS_HOUR_TO_MINUTE, SQL_IS_HOUR_TO_SECOND, &
    SQL_IS_MINUTE_TO_SECOND
 ! struct struct tagSQL_YEAR_MONTH
 type, public :: SQL_YEAR_MONTH_STRUCT
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_year => swigf_SQL_YEAR_MONTH_STRUCT_year_set
  procedure :: get_year => swigf_SQL_YEAR_MONTH_STRUCT_year_get
  procedure :: set_month => swigf_SQL_YEAR_MONTH_STRUCT_month_set
  procedure :: get_month => swigf_SQL_YEAR_MONTH_STRUCT_month_get
  procedure :: release => swigf_SQL_YEAR_MONTH_STRUCT_release
  procedure, private :: swigf_SQL_YEAR_MONTH_STRUCT_op_assign__
  generic :: assignment(=) => swigf_SQL_YEAR_MONTH_STRUCT_op_assign__
 end type SQL_YEAR_MONTH_STRUCT
 ! struct struct tagSQL_DAY_SECOND
 type, public :: SQL_DAY_SECOND_STRUCT
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_day => swigf_SQL_DAY_SECOND_STRUCT_day_set
  procedure :: get_day => swigf_SQL_DAY_SECOND_STRUCT_day_get
  procedure :: set_hour => swigf_SQL_DAY_SECOND_STRUCT_hour_set
  procedure :: get_hour => swigf_SQL_DAY_SECOND_STRUCT_hour_get
  procedure :: set_minute => swigf_SQL_DAY_SECOND_STRUCT_minute_set
  procedure :: get_minute => swigf_SQL_DAY_SECOND_STRUCT_minute_get
  procedure :: set_second => swigf_SQL_DAY_SECOND_STRUCT_second_set
  procedure :: get_second => swigf_SQL_DAY_SECOND_STRUCT_second_get
  procedure :: set_fraction => swigf_SQL_DAY_SECOND_STRUCT_fraction_set
  procedure :: get_fraction => swigf_SQL_DAY_SECOND_STRUCT_fraction_get
  procedure :: release => swigf_SQL_DAY_SECOND_STRUCT_release
  procedure, private :: swigf_SQL_DAY_SECOND_STRUCT_op_assign__
  generic :: assignment(=) => swigf_SQL_DAY_SECOND_STRUCT_op_assign__
 end type SQL_DAY_SECOND_STRUCT
 ! struct struct tagSQL_INTERVAL_STRUCT
 type, public :: SQL_INTERVAL_STRUCT
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_interval_type => swigf_SQL_INTERVAL_STRUCT_interval_type_set
  procedure :: get_interval_type => swigf_SQL_INTERVAL_STRUCT_interval_type_get
  procedure :: set_interval_sign => swigf_SQL_INTERVAL_STRUCT_interval_sign_set
  procedure :: get_interval_sign => swigf_SQL_INTERVAL_STRUCT_interval_sign_get
  procedure :: get_intval => swigf_SQL_INTERVAL_STRUCT_intval_get
  procedure :: release => swigf_SQL_INTERVAL_STRUCT_release
  procedure, private :: swigf_SQL_INTERVAL_STRUCT_op_assign__
  generic :: assignment(=) => swigf_SQL_INTERVAL_STRUCT_op_assign__
 end type SQL_INTERVAL_STRUCT
 ! union tagSQL_INTERVAL_STRUCT_intval
 type, public :: tagSQL_INTERVAL_STRUCT_intval
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_year_month => swigf_tagSQL_INTERVAL_STRUCT_intval_year_month_set
  procedure :: get_year_month => swigf_tagSQL_INTERVAL_STRUCT_intval_year_month_get
  procedure :: set_day_second => swigf_tagSQL_INTERVAL_STRUCT_intval_day_second_set
  procedure :: get_day_second => swigf_tagSQL_INTERVAL_STRUCT_intval_day_second_get
  procedure :: release => swigf_tagSQL_INTERVAL_STRUCT_intval_release
  procedure, private :: swigf_tagSQL_INTERVAL_STRUCT_intval_op_assign__
  generic :: assignment(=) => swigf_tagSQL_INTERVAL_STRUCT_intval_op_assign__
 end type tagSQL_INTERVAL_STRUCT_intval
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 public :: get_ODBCINT64_TYPE
 public :: get_UODBCINT64_TYPE
 public :: get_SQL_MAX_NUMERIC_LEN
 type, public :: SWIGTYPE_p_unsigned_char
  type(SwigClassWrapper), public :: swigdata
 end type
 ! struct struct tagSQL_NUMERIC_STRUCT
 type, public :: SQL_NUMERIC_STRUCT
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_precision => swigf_SQL_NUMERIC_STRUCT_precision_set
  procedure :: get_precision => swigf_SQL_NUMERIC_STRUCT_precision_get
  procedure :: set_scale => swigf_SQL_NUMERIC_STRUCT_scale_set
  procedure :: get_scale => swigf_SQL_NUMERIC_STRUCT_scale_get
  procedure :: set_sign => swigf_SQL_NUMERIC_STRUCT_sign_set
  procedure :: get_sign => swigf_SQL_NUMERIC_STRUCT_sign_get
  procedure :: set_val => swigf_SQL_NUMERIC_STRUCT_val_set
  procedure :: get_val => swigf_SQL_NUMERIC_STRUCT_val_get
  procedure :: release => swigf_SQL_NUMERIC_STRUCT_release
  procedure, private :: swigf_SQL_NUMERIC_STRUCT_op_assign__
  generic :: assignment(=) => swigf_SQL_NUMERIC_STRUCT_op_assign__
 end type SQL_NUMERIC_STRUCT
 ! struct struct tagSQLGUID
 type, public :: SQLGUID
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_Data1 => swigf_SQLGUID_Data1_set
  procedure :: get_Data1 => swigf_SQLGUID_Data1_get
  procedure :: set_Data2 => swigf_SQLGUID_Data2_set
  procedure :: get_Data2 => swigf_SQLGUID_Data2_get
  procedure :: set_Data3 => swigf_SQLGUID_Data3_set
  procedure :: get_Data3 => swigf_SQLGUID_Data3_get
  procedure :: set_Data4 => swigf_SQLGUID_Data4_set
  procedure :: get_Data4 => swigf_SQLGUID_Data4_get
  procedure :: release => swigf_SQLGUID_release
  procedure, private :: swigf_SQLGUID_op_assign__
  generic :: assignment(=) => swigf_SQLGUID_op_assign__
 end type SQLGUID
 interface SQL_YEAR_MONTH_STRUCT
  module procedure swigf_new_SQL_YEAR_MONTH_STRUCT
 end interface
 interface SQLGUID
  module procedure swigf_new_SQLGUID
 end interface
 interface SQL_DAY_SECOND_STRUCT
  module procedure swigf_new_SQL_DAY_SECOND_STRUCT
 end interface
 interface DATE_STRUCT
  module procedure swigf_new_DATE_STRUCT
 end interface
 interface tagSQL_INTERVAL_STRUCT_intval
  module procedure swigf_new_tagSQL_INTERVAL_STRUCT_intval
 end interface
 interface TIME_STRUCT
  module procedure swigf_new_TIME_STRUCT
 end interface
 interface TIMESTAMP_STRUCT
  module procedure swigf_new_TIMESTAMP_STRUCT
 end interface
 interface SQL_INTERVAL_STRUCT
  module procedure swigf_new_SQL_INTERVAL_STRUCT
 end interface
 interface SQL_NUMERIC_STRUCT
  module procedure swigf_new_SQL_NUMERIC_STRUCT
 end interface

! WRAPPER DECLARATIONS
interface
subroutine swigc_DATE_STRUCT_year_set(farg1, farg2) &
bind(C, name="_wrap_DATE_STRUCT_year_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_DATE_STRUCT_year_get(farg1) &
bind(C, name="_wrap_DATE_STRUCT_year_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_DATE_STRUCT_month_set(farg1, farg2) &
bind(C, name="_wrap_DATE_STRUCT_month_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_DATE_STRUCT_month_get(farg1) &
bind(C, name="_wrap_DATE_STRUCT_month_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_DATE_STRUCT_day_set(farg1, farg2) &
bind(C, name="_wrap_DATE_STRUCT_day_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_DATE_STRUCT_day_get(farg1) &
bind(C, name="_wrap_DATE_STRUCT_day_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

function swigc_new_DATE_STRUCT() &
bind(C, name="_wrap_new_DATE_STRUCT") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_DATE_STRUCT(farg1) &
bind(C, name="_wrap_delete_DATE_STRUCT")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_DATE_STRUCT_op_assign__(farg1, farg2) &
bind(C, name="_wrap_DATE_STRUCT_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_TIME_STRUCT_hour_set(farg1, farg2) &
bind(C, name="_wrap_TIME_STRUCT_hour_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIME_STRUCT_hour_get(farg1) &
bind(C, name="_wrap_TIME_STRUCT_hour_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIME_STRUCT_minute_set(farg1, farg2) &
bind(C, name="_wrap_TIME_STRUCT_minute_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIME_STRUCT_minute_get(farg1) &
bind(C, name="_wrap_TIME_STRUCT_minute_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIME_STRUCT_second_set(farg1, farg2) &
bind(C, name="_wrap_TIME_STRUCT_second_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIME_STRUCT_second_get(farg1) &
bind(C, name="_wrap_TIME_STRUCT_second_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

function swigc_new_TIME_STRUCT() &
bind(C, name="_wrap_new_TIME_STRUCT") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_TIME_STRUCT(farg1) &
bind(C, name="_wrap_delete_TIME_STRUCT")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_TIME_STRUCT_op_assign__(farg1, farg2) &
bind(C, name="_wrap_TIME_STRUCT_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_TIMESTAMP_STRUCT_year_set(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_year_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIMESTAMP_STRUCT_year_get(farg1) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_year_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIMESTAMP_STRUCT_month_set(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_month_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIMESTAMP_STRUCT_month_get(farg1) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_month_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIMESTAMP_STRUCT_day_set(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_day_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIMESTAMP_STRUCT_day_get(farg1) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_day_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIMESTAMP_STRUCT_hour_set(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_hour_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIMESTAMP_STRUCT_hour_get(farg1) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_hour_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIMESTAMP_STRUCT_minute_set(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_minute_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIMESTAMP_STRUCT_minute_get(farg1) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_minute_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIMESTAMP_STRUCT_second_set(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_second_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_TIMESTAMP_STRUCT_second_get(farg1) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_second_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_TIMESTAMP_STRUCT_fraction_set(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_fraction_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_TIMESTAMP_STRUCT_fraction_get(farg1) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_fraction_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_new_TIMESTAMP_STRUCT() &
bind(C, name="_wrap_new_TIMESTAMP_STRUCT") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_TIMESTAMP_STRUCT(farg1) &
bind(C, name="_wrap_delete_TIMESTAMP_STRUCT")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_TIMESTAMP_STRUCT_op_assign__(farg1, farg2) &
bind(C, name="_wrap_TIMESTAMP_STRUCT_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_SQL_YEAR_MONTH_STRUCT_year_set(farg1, farg2) &
bind(C, name="_wrap_SQL_YEAR_MONTH_STRUCT_year_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_YEAR_MONTH_STRUCT_year_get(farg1) &
bind(C, name="_wrap_SQL_YEAR_MONTH_STRUCT_year_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SQL_YEAR_MONTH_STRUCT_month_set(farg1, farg2) &
bind(C, name="_wrap_SQL_YEAR_MONTH_STRUCT_month_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_YEAR_MONTH_STRUCT_month_get(farg1) &
bind(C, name="_wrap_SQL_YEAR_MONTH_STRUCT_month_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_new_SQL_YEAR_MONTH_STRUCT() &
bind(C, name="_wrap_new_SQL_YEAR_MONTH_STRUCT") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SQL_YEAR_MONTH_STRUCT(farg1) &
bind(C, name="_wrap_delete_SQL_YEAR_MONTH_STRUCT")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SQL_YEAR_MONTH_STRUCT_op_assign__(farg1, farg2) &
bind(C, name="_wrap_SQL_YEAR_MONTH_STRUCT_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_SQL_DAY_SECOND_STRUCT_day_set(farg1, farg2) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_day_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_DAY_SECOND_STRUCT_day_get(farg1) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_day_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SQL_DAY_SECOND_STRUCT_hour_set(farg1, farg2) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_hour_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_DAY_SECOND_STRUCT_hour_get(farg1) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_hour_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SQL_DAY_SECOND_STRUCT_minute_set(farg1, farg2) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_minute_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_DAY_SECOND_STRUCT_minute_get(farg1) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_minute_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SQL_DAY_SECOND_STRUCT_second_set(farg1, farg2) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_second_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_DAY_SECOND_STRUCT_second_get(farg1) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_second_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SQL_DAY_SECOND_STRUCT_fraction_set(farg1, farg2) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_fraction_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_DAY_SECOND_STRUCT_fraction_get(farg1) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_fraction_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_new_SQL_DAY_SECOND_STRUCT() &
bind(C, name="_wrap_new_SQL_DAY_SECOND_STRUCT") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SQL_DAY_SECOND_STRUCT(farg1) &
bind(C, name="_wrap_delete_SQL_DAY_SECOND_STRUCT")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SQL_DAY_SECOND_STRUCT_op_assign__(farg1, farg2) &
bind(C, name="_wrap_SQL_DAY_SECOND_STRUCT_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_SQL_INTERVAL_STRUCT_interval_type_set(farg1, farg2) &
bind(C, name="_wrap_SQL_INTERVAL_STRUCT_interval_type_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQL_INTERVAL_STRUCT_interval_type_get(farg1) &
bind(C, name="_wrap_SQL_INTERVAL_STRUCT_interval_type_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SQL_INTERVAL_STRUCT_interval_sign_set(farg1, farg2) &
bind(C, name="_wrap_SQL_INTERVAL_STRUCT_interval_sign_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_SQL_INTERVAL_STRUCT_interval_sign_get(farg1) &
bind(C, name="_wrap_SQL_INTERVAL_STRUCT_interval_sign_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

function swigc_SQL_INTERVAL_STRUCT_intval_get(farg1) &
bind(C, name="_wrap_SQL_INTERVAL_STRUCT_intval_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_SQL_INTERVAL_STRUCT() &
bind(C, name="_wrap_new_SQL_INTERVAL_STRUCT") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SQL_INTERVAL_STRUCT(farg1) &
bind(C, name="_wrap_delete_SQL_INTERVAL_STRUCT")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SQL_INTERVAL_STRUCT_op_assign__(farg1, farg2) &
bind(C, name="_wrap_SQL_INTERVAL_STRUCT_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_tagSQL_INTERVAL_STRUCT_intval_year_month_set(farg1, farg2) &
bind(C, name="_wrap_tagSQL_INTERVAL_STRUCT_intval_year_month_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_tagSQL_INTERVAL_STRUCT_intval_year_month_get(farg1) &
bind(C, name="_wrap_tagSQL_INTERVAL_STRUCT_intval_year_month_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_tagSQL_INTERVAL_STRUCT_intval_day_second_set(farg1, farg2) &
bind(C, name="_wrap_tagSQL_INTERVAL_STRUCT_intval_day_second_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_tagSQL_INTERVAL_STRUCT_intval_day_second_get(farg1) &
bind(C, name="_wrap_tagSQL_INTERVAL_STRUCT_intval_day_second_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_tagSQL_INTERVAL_STRUCT_intval() &
bind(C, name="_wrap_new_tagSQL_INTERVAL_STRUCT_intval") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_tagSQL_INTERVAL_STRUCT_intval(farg1) &
bind(C, name="_wrap_delete_tagSQL_INTERVAL_STRUCT_intval")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_tagSQL_INTERVAL_STRUCT_intval_op_assign__(farg1, farg2) &
bind(C, name="_wrap_tagSQL_INTERVAL_STRUCT_intval_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

 subroutine SWIG_free(cptr) &
  bind(C, name="free")
 use, intrinsic :: ISO_C_BINDING
 type(C_PTR), value :: cptr
end subroutine
function swigc_ODBCINT64_TYPE_get() &
bind(C, name="_wrap_ODBCINT64_TYPE_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: fresult
end function

function swigc_UODBCINT64_TYPE_get() &
bind(C, name="_wrap_UODBCINT64_TYPE_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: fresult
end function

function swigc_SQL_MAX_NUMERIC_LEN_get() &
bind(C, name="_wrap_SQL_MAX_NUMERIC_LEN_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

subroutine swigc_SQL_NUMERIC_STRUCT_precision_set(farg1, farg2) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_precision_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIGNED_CHAR), intent(in) :: farg2
end subroutine

function swigc_SQL_NUMERIC_STRUCT_precision_get(farg1) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_precision_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIGNED_CHAR) :: fresult
end function

subroutine swigc_SQL_NUMERIC_STRUCT_scale_set(farg1, farg2) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_scale_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIGNED_CHAR), intent(in) :: farg2
end subroutine

function swigc_SQL_NUMERIC_STRUCT_scale_get(farg1) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_scale_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIGNED_CHAR) :: fresult
end function

subroutine swigc_SQL_NUMERIC_STRUCT_sign_set(farg1, farg2) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_sign_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIGNED_CHAR), intent(in) :: farg2
end subroutine

function swigc_SQL_NUMERIC_STRUCT_sign_get(farg1) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_sign_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIGNED_CHAR) :: fresult
end function

subroutine swigc_SQL_NUMERIC_STRUCT_val_set(farg1, farg2) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_val_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_SQL_NUMERIC_STRUCT_val_get(farg1) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_val_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_SQL_NUMERIC_STRUCT() &
bind(C, name="_wrap_new_SQL_NUMERIC_STRUCT") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SQL_NUMERIC_STRUCT(farg1) &
bind(C, name="_wrap_delete_SQL_NUMERIC_STRUCT")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SQL_NUMERIC_STRUCT_op_assign__(farg1, farg2) &
bind(C, name="_wrap_SQL_NUMERIC_STRUCT_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_SQLGUID_Data1_set(farg1, farg2) &
bind(C, name="_wrap_SQLGUID_Data1_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SQLGUID_Data1_get(farg1) &
bind(C, name="_wrap_SQLGUID_Data1_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SQLGUID_Data2_set(farg1, farg2) &
bind(C, name="_wrap_SQLGUID_Data2_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_SQLGUID_Data2_get(farg1) &
bind(C, name="_wrap_SQLGUID_Data2_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_SQLGUID_Data3_set(farg1, farg2) &
bind(C, name="_wrap_SQLGUID_Data3_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT), intent(in) :: farg2
end subroutine

function swigc_SQLGUID_Data3_get(farg1) &
bind(C, name="_wrap_SQLGUID_Data3_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SHORT) :: fresult
end function

subroutine swigc_SQLGUID_Data4_set(farg1, farg2) &
bind(C, name="_wrap_SQLGUID_Data4_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_SQLGUID_Data4_get(farg1) &
bind(C, name="_wrap_SQLGUID_Data4_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_SQLGUID() &
bind(C, name="_wrap_new_SQLGUID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SQLGUID(farg1) &
bind(C, name="_wrap_delete_SQLGUID")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SQLGUID_op_assign__(farg1, farg2) &
bind(C, name="_wrap_SQLGUID_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine swigf_DATE_STRUCT_year_set(self, year)
use, intrinsic :: ISO_C_BINDING
class(DATE_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: year
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = year
call swigc_DATE_STRUCT_year_set(farg1, farg2)
end subroutine

function swigf_DATE_STRUCT_year_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(DATE_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_DATE_STRUCT_year_get(farg1)
swig_result = fresult
end function

subroutine swigf_DATE_STRUCT_month_set(self, month)
use, intrinsic :: ISO_C_BINDING
class(DATE_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: month
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = month
call swigc_DATE_STRUCT_month_set(farg1, farg2)
end subroutine

function swigf_DATE_STRUCT_month_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(DATE_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_DATE_STRUCT_month_get(farg1)
swig_result = fresult
end function

subroutine swigf_DATE_STRUCT_day_set(self, day)
use, intrinsic :: ISO_C_BINDING
class(DATE_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: day
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = day
call swigc_DATE_STRUCT_day_set(farg1, farg2)
end subroutine

function swigf_DATE_STRUCT_day_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(DATE_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_DATE_STRUCT_day_get(farg1)
swig_result = fresult
end function

function swigf_new_DATE_STRUCT() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(DATE_STRUCT) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_DATE_STRUCT()
self%swigdata = fresult
end function

subroutine swigf_DATE_STRUCT_release(self)
use, intrinsic :: ISO_C_BINDING
class(DATE_STRUCT), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_DATE_STRUCT(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_DATE_STRUCT_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(DATE_STRUCT), intent(inout) :: self
type(DATE_STRUCT), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_DATE_STRUCT_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_TIME_STRUCT_hour_set(self, hour)
use, intrinsic :: ISO_C_BINDING
class(TIME_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: hour
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = hour
call swigc_TIME_STRUCT_hour_set(farg1, farg2)
end subroutine

function swigf_TIME_STRUCT_hour_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIME_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIME_STRUCT_hour_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIME_STRUCT_minute_set(self, minute)
use, intrinsic :: ISO_C_BINDING
class(TIME_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: minute
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = minute
call swigc_TIME_STRUCT_minute_set(farg1, farg2)
end subroutine

function swigf_TIME_STRUCT_minute_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIME_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIME_STRUCT_minute_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIME_STRUCT_second_set(self, second)
use, intrinsic :: ISO_C_BINDING
class(TIME_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: second
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = second
call swigc_TIME_STRUCT_second_set(farg1, farg2)
end subroutine

function swigf_TIME_STRUCT_second_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIME_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIME_STRUCT_second_get(farg1)
swig_result = fresult
end function

function swigf_new_TIME_STRUCT() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(TIME_STRUCT) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_TIME_STRUCT()
self%swigdata = fresult
end function

subroutine swigf_TIME_STRUCT_release(self)
use, intrinsic :: ISO_C_BINDING
class(TIME_STRUCT), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_TIME_STRUCT(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_TIME_STRUCT_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(TIME_STRUCT), intent(inout) :: self
type(TIME_STRUCT), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_TIME_STRUCT_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_TIMESTAMP_STRUCT_year_set(self, year)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: year
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = year
call swigc_TIMESTAMP_STRUCT_year_set(farg1, farg2)
end subroutine

function swigf_TIMESTAMP_STRUCT_year_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIMESTAMP_STRUCT_year_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIMESTAMP_STRUCT_month_set(self, month)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: month
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = month
call swigc_TIMESTAMP_STRUCT_month_set(farg1, farg2)
end subroutine

function swigf_TIMESTAMP_STRUCT_month_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIMESTAMP_STRUCT_month_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIMESTAMP_STRUCT_day_set(self, day)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: day
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = day
call swigc_TIMESTAMP_STRUCT_day_set(farg1, farg2)
end subroutine

function swigf_TIMESTAMP_STRUCT_day_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIMESTAMP_STRUCT_day_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIMESTAMP_STRUCT_hour_set(self, hour)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: hour
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = hour
call swigc_TIMESTAMP_STRUCT_hour_set(farg1, farg2)
end subroutine

function swigf_TIMESTAMP_STRUCT_hour_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIMESTAMP_STRUCT_hour_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIMESTAMP_STRUCT_minute_set(self, minute)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: minute
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = minute
call swigc_TIMESTAMP_STRUCT_minute_set(farg1, farg2)
end subroutine

function swigf_TIMESTAMP_STRUCT_minute_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIMESTAMP_STRUCT_minute_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIMESTAMP_STRUCT_second_set(self, second)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: second
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = second
call swigc_TIMESTAMP_STRUCT_second_set(farg1, farg2)
end subroutine

function swigf_TIMESTAMP_STRUCT_second_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIMESTAMP_STRUCT_second_get(farg1)
swig_result = fresult
end function

subroutine swigf_TIMESTAMP_STRUCT_fraction_set(self, fraction)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: fraction
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = fraction
call swigc_TIMESTAMP_STRUCT_fraction_set(farg1, farg2)
end subroutine

function swigf_TIMESTAMP_STRUCT_fraction_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(TIMESTAMP_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TIMESTAMP_STRUCT_fraction_get(farg1)
swig_result = fresult
end function

function swigf_new_TIMESTAMP_STRUCT() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(TIMESTAMP_STRUCT) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_TIMESTAMP_STRUCT()
self%swigdata = fresult
end function

subroutine swigf_TIMESTAMP_STRUCT_release(self)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_TIMESTAMP_STRUCT(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_TIMESTAMP_STRUCT_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(TIMESTAMP_STRUCT), intent(inout) :: self
type(TIMESTAMP_STRUCT), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_TIMESTAMP_STRUCT_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_SQL_YEAR_MONTH_STRUCT_year_set(self, year)
use, intrinsic :: ISO_C_BINDING
class(SQL_YEAR_MONTH_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: year
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = year
call swigc_SQL_YEAR_MONTH_STRUCT_year_set(farg1, farg2)
end subroutine

function swigf_SQL_YEAR_MONTH_STRUCT_year_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQL_YEAR_MONTH_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_YEAR_MONTH_STRUCT_year_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_YEAR_MONTH_STRUCT_month_set(self, month)
use, intrinsic :: ISO_C_BINDING
class(SQL_YEAR_MONTH_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: month
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = month
call swigc_SQL_YEAR_MONTH_STRUCT_month_set(farg1, farg2)
end subroutine

function swigf_SQL_YEAR_MONTH_STRUCT_month_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQL_YEAR_MONTH_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_YEAR_MONTH_STRUCT_month_get(farg1)
swig_result = fresult
end function

function swigf_new_SQL_YEAR_MONTH_STRUCT() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SQL_YEAR_MONTH_STRUCT) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SQL_YEAR_MONTH_STRUCT()
self%swigdata = fresult
end function

subroutine swigf_SQL_YEAR_MONTH_STRUCT_release(self)
use, intrinsic :: ISO_C_BINDING
class(SQL_YEAR_MONTH_STRUCT), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SQL_YEAR_MONTH_STRUCT(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SQL_YEAR_MONTH_STRUCT_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SQL_YEAR_MONTH_STRUCT), intent(inout) :: self
type(SQL_YEAR_MONTH_STRUCT), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SQL_YEAR_MONTH_STRUCT_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_SQL_DAY_SECOND_STRUCT_day_set(self, day)
use, intrinsic :: ISO_C_BINDING
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: day
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = day
call swigc_SQL_DAY_SECOND_STRUCT_day_set(farg1, farg2)
end subroutine

function swigf_SQL_DAY_SECOND_STRUCT_day_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_DAY_SECOND_STRUCT_day_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_DAY_SECOND_STRUCT_hour_set(self, hour)
use, intrinsic :: ISO_C_BINDING
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: hour
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = hour
call swigc_SQL_DAY_SECOND_STRUCT_hour_set(farg1, farg2)
end subroutine

function swigf_SQL_DAY_SECOND_STRUCT_hour_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_DAY_SECOND_STRUCT_hour_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_DAY_SECOND_STRUCT_minute_set(self, minute)
use, intrinsic :: ISO_C_BINDING
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: minute
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = minute
call swigc_SQL_DAY_SECOND_STRUCT_minute_set(farg1, farg2)
end subroutine

function swigf_SQL_DAY_SECOND_STRUCT_minute_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_DAY_SECOND_STRUCT_minute_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_DAY_SECOND_STRUCT_second_set(self, second)
use, intrinsic :: ISO_C_BINDING
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: second
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = second
call swigc_SQL_DAY_SECOND_STRUCT_second_set(farg1, farg2)
end subroutine

function swigf_SQL_DAY_SECOND_STRUCT_second_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_DAY_SECOND_STRUCT_second_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_DAY_SECOND_STRUCT_fraction_set(self, fraction)
use, intrinsic :: ISO_C_BINDING
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT), intent(in) :: fraction
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = fraction
call swigc_SQL_DAY_SECOND_STRUCT_fraction_set(farg1, farg2)
end subroutine

function swigf_SQL_DAY_SECOND_STRUCT_fraction_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQL_DAY_SECOND_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_DAY_SECOND_STRUCT_fraction_get(farg1)
swig_result = fresult
end function

function swigf_new_SQL_DAY_SECOND_STRUCT() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SQL_DAY_SECOND_STRUCT) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SQL_DAY_SECOND_STRUCT()
self%swigdata = fresult
end function

subroutine swigf_SQL_DAY_SECOND_STRUCT_release(self)
use, intrinsic :: ISO_C_BINDING
class(SQL_DAY_SECOND_STRUCT), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SQL_DAY_SECOND_STRUCT(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SQL_DAY_SECOND_STRUCT_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SQL_DAY_SECOND_STRUCT), intent(inout) :: self
type(SQL_DAY_SECOND_STRUCT), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SQL_DAY_SECOND_STRUCT_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_SQL_INTERVAL_STRUCT_interval_type_set(self, interval_type)
use, intrinsic :: ISO_C_BINDING
class(SQL_INTERVAL_STRUCT), intent(in) :: self
integer(SQLINTERVAL), intent(in) :: interval_type
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = interval_type
call swigc_SQL_INTERVAL_STRUCT_interval_type_set(farg1, farg2)
end subroutine

function swigf_SQL_INTERVAL_STRUCT_interval_type_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SQLINTERVAL) :: swig_result
class(SQL_INTERVAL_STRUCT), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_INTERVAL_STRUCT_interval_type_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_INTERVAL_STRUCT_interval_sign_set(self, interval_sign)
use, intrinsic :: ISO_C_BINDING
class(SQL_INTERVAL_STRUCT), intent(in) :: self
integer(C_SHORT), intent(in) :: interval_sign
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = interval_sign
call swigc_SQL_INTERVAL_STRUCT_interval_sign_set(farg1, farg2)
end subroutine

function swigf_SQL_INTERVAL_STRUCT_interval_sign_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(SQL_INTERVAL_STRUCT), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_INTERVAL_STRUCT_interval_sign_get(farg1)
swig_result = fresult
end function

function swigf_SQL_INTERVAL_STRUCT_intval_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(tagSQL_INTERVAL_STRUCT_intval) :: swig_result
class(SQL_INTERVAL_STRUCT), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_INTERVAL_STRUCT_intval_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_SQL_INTERVAL_STRUCT() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SQL_INTERVAL_STRUCT) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SQL_INTERVAL_STRUCT()
self%swigdata = fresult
end function

subroutine swigf_SQL_INTERVAL_STRUCT_release(self)
use, intrinsic :: ISO_C_BINDING
class(SQL_INTERVAL_STRUCT), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SQL_INTERVAL_STRUCT(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SQL_INTERVAL_STRUCT_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SQL_INTERVAL_STRUCT), intent(inout) :: self
type(SQL_INTERVAL_STRUCT), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SQL_INTERVAL_STRUCT_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_tagSQL_INTERVAL_STRUCT_intval_year_month_set(self, year_month)
use, intrinsic :: ISO_C_BINDING
class(tagSQL_INTERVAL_STRUCT_intval), intent(in) :: self
class(SQL_YEAR_MONTH_STRUCT), intent(in) :: year_month
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = year_month%swigdata
call swigc_tagSQL_INTERVAL_STRUCT_intval_year_month_set(farg1, farg2)
end subroutine

function swigf_tagSQL_INTERVAL_STRUCT_intval_year_month_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SQL_YEAR_MONTH_STRUCT) :: swig_result
class(tagSQL_INTERVAL_STRUCT_intval), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_tagSQL_INTERVAL_STRUCT_intval_year_month_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_tagSQL_INTERVAL_STRUCT_intval_day_second_set(self, day_second)
use, intrinsic :: ISO_C_BINDING
class(tagSQL_INTERVAL_STRUCT_intval), intent(in) :: self
class(SQL_DAY_SECOND_STRUCT), intent(in) :: day_second
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = day_second%swigdata
call swigc_tagSQL_INTERVAL_STRUCT_intval_day_second_set(farg1, farg2)
end subroutine

function swigf_tagSQL_INTERVAL_STRUCT_intval_day_second_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SQL_DAY_SECOND_STRUCT) :: swig_result
class(tagSQL_INTERVAL_STRUCT_intval), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_tagSQL_INTERVAL_STRUCT_intval_day_second_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_tagSQL_INTERVAL_STRUCT_intval() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(tagSQL_INTERVAL_STRUCT_intval) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_tagSQL_INTERVAL_STRUCT_intval()
self%swigdata = fresult
end function

subroutine swigf_tagSQL_INTERVAL_STRUCT_intval_release(self)
use, intrinsic :: ISO_C_BINDING
class(tagSQL_INTERVAL_STRUCT_intval), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_tagSQL_INTERVAL_STRUCT_intval(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_tagSQL_INTERVAL_STRUCT_intval_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(tagSQL_INTERVAL_STRUCT_intval), intent(inout) :: self
type(tagSQL_INTERVAL_STRUCT_intval), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_tagSQL_INTERVAL_STRUCT_intval_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine


subroutine SWIGTM_fout_char_Sm_(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(in) :: imout
  character(len=:), allocatable, intent(out) :: fout
  character(kind=C_CHAR), dimension(:), pointer :: chars
  integer(kind=C_SIZE_T) :: i
  call c_f_pointer(imout%data, chars, [imout%size])
  allocate(character(len=imout%size) :: fout)
  do i=1, imout%size
    fout(i:i) = char(ichar(chars(i)))
  end do
end subroutine

function get_ODBCINT64_TYPE() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(len=:), allocatable :: swig_result
type(SwigArrayWrapper) :: fresult 

fresult = swigc_ODBCINT64_TYPE_get()
call SWIGTM_fout_char_Sm_(fresult, swig_result)
if (.false.) call SWIG_free(fresult%data)
end function

function get_UODBCINT64_TYPE() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(len=:), allocatable :: swig_result
type(SwigArrayWrapper) :: fresult 

fresult = swigc_UODBCINT64_TYPE_get()
call SWIGTM_fout_char_Sm_(fresult, swig_result)
if (.false.) call SWIG_free(fresult%data)
end function

function get_SQL_MAX_NUMERIC_LEN() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_SQL_MAX_NUMERIC_LEN_get()
swig_result = fresult
end function

subroutine swigf_SQL_NUMERIC_STRUCT_precision_set(self, precision)
use, intrinsic :: ISO_C_BINDING
class(SQL_NUMERIC_STRUCT), intent(in) :: self
integer(C_SIGNED_CHAR), intent(in) :: precision
type(SwigClassWrapper) :: farg1 
integer(C_SIGNED_CHAR) :: farg2 

farg1 = self%swigdata
farg2 = precision
call swigc_SQL_NUMERIC_STRUCT_precision_set(farg1, farg2)
end subroutine

function swigf_SQL_NUMERIC_STRUCT_precision_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SIGNED_CHAR) :: swig_result
class(SQL_NUMERIC_STRUCT), intent(in) :: self
integer(C_SIGNED_CHAR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_NUMERIC_STRUCT_precision_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_NUMERIC_STRUCT_scale_set(self, scale)
use, intrinsic :: ISO_C_BINDING
class(SQL_NUMERIC_STRUCT), intent(in) :: self
integer(C_SIGNED_CHAR), intent(in) :: scale
type(SwigClassWrapper) :: farg1 
integer(C_SIGNED_CHAR) :: farg2 

farg1 = self%swigdata
farg2 = scale
call swigc_SQL_NUMERIC_STRUCT_scale_set(farg1, farg2)
end subroutine

function swigf_SQL_NUMERIC_STRUCT_scale_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SIGNED_CHAR) :: swig_result
class(SQL_NUMERIC_STRUCT), intent(in) :: self
integer(C_SIGNED_CHAR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_NUMERIC_STRUCT_scale_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_NUMERIC_STRUCT_sign_set(self, sign)
use, intrinsic :: ISO_C_BINDING
class(SQL_NUMERIC_STRUCT), intent(in) :: self
integer(C_SIGNED_CHAR), intent(in) :: sign
type(SwigClassWrapper) :: farg1 
integer(C_SIGNED_CHAR) :: farg2 

farg1 = self%swigdata
farg2 = sign
call swigc_SQL_NUMERIC_STRUCT_sign_set(farg1, farg2)
end subroutine

function swigf_SQL_NUMERIC_STRUCT_sign_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SIGNED_CHAR) :: swig_result
class(SQL_NUMERIC_STRUCT), intent(in) :: self
integer(C_SIGNED_CHAR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_NUMERIC_STRUCT_sign_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQL_NUMERIC_STRUCT_val_set(self, val)
use, intrinsic :: ISO_C_BINDING
class(SQL_NUMERIC_STRUCT), intent(in) :: self
class(SWIGTYPE_p_unsigned_char), intent(in) :: val
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = val%swigdata
call swigc_SQL_NUMERIC_STRUCT_val_set(farg1, farg2)
end subroutine

function swigf_SQL_NUMERIC_STRUCT_val_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_unsigned_char) :: swig_result
class(SQL_NUMERIC_STRUCT), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQL_NUMERIC_STRUCT_val_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_SQL_NUMERIC_STRUCT() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SQL_NUMERIC_STRUCT) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SQL_NUMERIC_STRUCT()
self%swigdata = fresult
end function

subroutine swigf_SQL_NUMERIC_STRUCT_release(self)
use, intrinsic :: ISO_C_BINDING
class(SQL_NUMERIC_STRUCT), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SQL_NUMERIC_STRUCT(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SQL_NUMERIC_STRUCT_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SQL_NUMERIC_STRUCT), intent(inout) :: self
type(SQL_NUMERIC_STRUCT), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SQL_NUMERIC_STRUCT_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_SQLGUID_Data1_set(self, data1)
use, intrinsic :: ISO_C_BINDING
class(SQLGUID), intent(in) :: self
integer(C_INT), intent(in) :: data1
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = data1
call swigc_SQLGUID_Data1_set(farg1, farg2)
end subroutine

function swigf_SQLGUID_Data1_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SQLGUID), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQLGUID_Data1_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQLGUID_Data2_set(self, data2)
use, intrinsic :: ISO_C_BINDING
class(SQLGUID), intent(in) :: self
integer(C_SHORT), intent(in) :: data2
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = data2
call swigc_SQLGUID_Data2_set(farg1, farg2)
end subroutine

function swigf_SQLGUID_Data2_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(SQLGUID), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQLGUID_Data2_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQLGUID_Data3_set(self, data3)
use, intrinsic :: ISO_C_BINDING
class(SQLGUID), intent(in) :: self
integer(C_SHORT), intent(in) :: data3
type(SwigClassWrapper) :: farg1 
integer(C_SHORT) :: farg2 

farg1 = self%swigdata
farg2 = data3
call swigc_SQLGUID_Data3_set(farg1, farg2)
end subroutine

function swigf_SQLGUID_Data3_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SHORT) :: swig_result
class(SQLGUID), intent(in) :: self
integer(C_SHORT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQLGUID_Data3_get(farg1)
swig_result = fresult
end function

subroutine swigf_SQLGUID_Data4_set(self, data4)
use, intrinsic :: ISO_C_BINDING
class(SQLGUID), intent(in) :: self
class(SWIGTYPE_p_unsigned_char), intent(in) :: data4
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = data4%swigdata
call swigc_SQLGUID_Data4_set(farg1, farg2)
end subroutine

function swigf_SQLGUID_Data4_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_unsigned_char) :: swig_result
class(SQLGUID), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SQLGUID_Data4_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_SQLGUID() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SQLGUID) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SQLGUID()
self%swigdata = fresult
end function

subroutine swigf_SQLGUID_release(self)
use, intrinsic :: ISO_C_BINDING
class(SQLGUID), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SQLGUID(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SQLGUID_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SQLGUID), intent(inout) :: self
type(SQLGUID), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SQLGUID_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine


end module
