! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module sqltypes
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 ! struct struct tagDATE_STRUCT
 type, bind(C), public :: DATE_STRUCT
  integer(c_short), public :: year
  integer(c_short), public :: month
  integer(c_short), public :: day
 end type DATE_STRUCT
 ! struct struct tagTIME_STRUCT
 type, bind(C), public :: TIME_STRUCT
  integer(c_short), public :: hour
  integer(c_short), public :: minute
  integer(c_short), public :: second
 end type TIME_STRUCT
 ! struct struct tagTIMESTAMP_STRUCT
 type, bind(C), public :: TIMESTAMP_STRUCT
  integer(c_short), public :: year
  integer(c_short), public :: month
  integer(c_short), public :: day
  integer(c_short), public :: hour
  integer(c_short), public :: minute
  integer(c_short), public :: second
  integer(C_INT), public :: fraction
 end type TIMESTAMP_STRUCT
 ! typedef enum SQLINTERVAL
 enum, bind(c)
  enumerator :: SQL_IS_YEAR = 1
  enumerator :: SQL_IS_MONTH = 2
  enumerator :: SQL_IS_DAY = 3
  enumerator :: SQL_IS_HOUR = 4
  enumerator :: SQL_IS_MINUTE = 5
  enumerator :: SQL_IS_SECOND = 6
  enumerator :: SQL_IS_YEAR_TO_MONTH = 7
  enumerator :: SQL_IS_DAY_TO_HOUR = 8
  enumerator :: SQL_IS_DAY_TO_MINUTE = 9
  enumerator :: SQL_IS_DAY_TO_SECOND = 10
  enumerator :: SQL_IS_HOUR_TO_MINUTE = 11
  enumerator :: SQL_IS_HOUR_TO_SECOND = 12
  enumerator :: SQL_IS_MINUTE_TO_SECOND = 13
 end enum
 integer, parameter, public :: SQLINTERVAL = kind(SQL_IS_YEAR)
 public :: SQL_IS_YEAR, SQL_IS_MONTH, SQL_IS_DAY, SQL_IS_HOUR, SQL_IS_MINUTE, SQL_IS_SECOND, SQL_IS_YEAR_TO_MONTH, &
    SQL_IS_DAY_TO_HOUR, SQL_IS_DAY_TO_MINUTE, SQL_IS_DAY_TO_SECOND, SQL_IS_HOUR_TO_MINUTE, SQL_IS_HOUR_TO_SECOND, &
    SQL_IS_MINUTE_TO_SECOND
 ! struct struct tagSQL_YEAR_MONTH
 type, bind(C), public :: SQL_YEAR_MONTH_STRUCT
  integer(C_INT), public :: year
  integer(C_INT), public :: month
 end type SQL_YEAR_MONTH_STRUCT
 ! struct struct tagSQL_DAY_SECOND
 type, bind(C), public :: SQL_DAY_SECOND_STRUCT
  integer(C_INT), public :: day
  integer(C_INT), public :: hour
  integer(C_INT), public :: minute
  integer(C_INT), public :: second
  integer(C_INT), public :: fraction
 end type SQL_DAY_SECOND_STRUCT
 integer(C_INT), parameter, public :: SQL_MAX_NUMERIC_LEN = 16_C_INT
 ! struct struct tagSQL_NUMERIC_STRUCT
 type, bind(C), public :: SQL_NUMERIC_STRUCT
  character(kind=c_char), public :: precision
  integer(C_SIGNED_CHAR), public :: scale
  character(kind=c_char), public :: sign
  integer(C_SIGNED_CHAR), dimension(16), public :: val
 end type SQL_NUMERIC_STRUCT
 ! struct struct tagSQLGUID
 type, bind(C), public :: SQLGUID
  integer(c_long), public :: Data1
  integer(c_short), public :: Data2
  integer(c_short), public :: Data3
  integer(C_SIGNED_CHAR), dimension(8), public :: Data4
 end type SQLGUID

end module
