/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 


/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif



#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};


#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(PTR)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }



#define SWIG_VERSION 0x040200
#define SWIGFORTRAN

#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 

                // This adds the include to the generated wrapper.
#include "../include/sqltypes.h"


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else if (self->cptr == other.cptr) {
    /* Self-assignment: ignore */
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}

typedef union {
  SQL_YEAR_MONTH_STRUCT		year_month;
  SQL_DAY_SECOND_STRUCT		day_second;
} tagSQL_INTERVAL_STRUCT_intval;


typedef struct {
    void* data;
    size_t size;
} SwigArrayWrapper;


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}

SWIGEXPORT void _wrap_DATE_STRUCT_year_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  SQLSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagDATE_STRUCT *", "DATE_STRUCT", "tagDATE_STRUCT::year", return );
  arg1 = (struct tagDATE_STRUCT *)farg1->cptr;
  arg2 = (SQLSMALLINT)(*farg2);
  if (arg1) (arg1)->year = arg2;
}


SWIGEXPORT short _wrap_DATE_STRUCT_year_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  SQLSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagDATE_STRUCT *", "DATE_STRUCT", "tagDATE_STRUCT::year", return 0);
  arg1 = (struct tagDATE_STRUCT *)farg1->cptr;
  result = (SQLSMALLINT) ((arg1)->year);
  fresult = (SQLSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_DATE_STRUCT_month_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagDATE_STRUCT *", "DATE_STRUCT", "tagDATE_STRUCT::month", return );
  arg1 = (struct tagDATE_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->month = arg2;
}


SWIGEXPORT short _wrap_DATE_STRUCT_month_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagDATE_STRUCT *", "DATE_STRUCT", "tagDATE_STRUCT::month", return 0);
  arg1 = (struct tagDATE_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->month);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_DATE_STRUCT_day_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagDATE_STRUCT *", "DATE_STRUCT", "tagDATE_STRUCT::day", return );
  arg1 = (struct tagDATE_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->day = arg2;
}


SWIGEXPORT short _wrap_DATE_STRUCT_day_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagDATE_STRUCT *", "DATE_STRUCT", "tagDATE_STRUCT::day", return 0);
  arg1 = (struct tagDATE_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->day);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_DATE_STRUCT() {
  SwigClassWrapper fresult ;
  struct tagDATE_STRUCT *result = 0 ;
  
  result = (struct tagDATE_STRUCT *)calloc(1, sizeof(struct tagDATE_STRUCT));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_DATE_STRUCT(SwigClassWrapper *farg1) {
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  
  arg1 = (struct tagDATE_STRUCT *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_DATE_STRUCT_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagDATE_STRUCT *arg1 = (struct tagDATE_STRUCT *) 0 ;
  struct tagDATE_STRUCT *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_TIME_STRUCT_hour_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIME_STRUCT *", "TIME_STRUCT", "tagTIME_STRUCT::hour", return );
  arg1 = (struct tagTIME_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->hour = arg2;
}


SWIGEXPORT short _wrap_TIME_STRUCT_hour_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIME_STRUCT *", "TIME_STRUCT", "tagTIME_STRUCT::hour", return 0);
  arg1 = (struct tagTIME_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->hour);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIME_STRUCT_minute_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIME_STRUCT *", "TIME_STRUCT", "tagTIME_STRUCT::minute", return );
  arg1 = (struct tagTIME_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->minute = arg2;
}


SWIGEXPORT short _wrap_TIME_STRUCT_minute_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIME_STRUCT *", "TIME_STRUCT", "tagTIME_STRUCT::minute", return 0);
  arg1 = (struct tagTIME_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->minute);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIME_STRUCT_second_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIME_STRUCT *", "TIME_STRUCT", "tagTIME_STRUCT::second", return );
  arg1 = (struct tagTIME_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->second = arg2;
}


SWIGEXPORT short _wrap_TIME_STRUCT_second_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIME_STRUCT *", "TIME_STRUCT", "tagTIME_STRUCT::second", return 0);
  arg1 = (struct tagTIME_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->second);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_TIME_STRUCT() {
  SwigClassWrapper fresult ;
  struct tagTIME_STRUCT *result = 0 ;
  
  result = (struct tagTIME_STRUCT *)calloc(1, sizeof(struct tagTIME_STRUCT));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_TIME_STRUCT(SwigClassWrapper *farg1) {
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  
  arg1 = (struct tagTIME_STRUCT *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_TIME_STRUCT_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagTIME_STRUCT *arg1 = (struct tagTIME_STRUCT *) 0 ;
  struct tagTIME_STRUCT *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_year_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::year", return );
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  arg2 = (SQLSMALLINT)(*farg2);
  if (arg1) (arg1)->year = arg2;
}


SWIGEXPORT short _wrap_TIMESTAMP_STRUCT_year_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::year", return 0);
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  result = (SQLSMALLINT) ((arg1)->year);
  fresult = (SQLSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_month_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::month", return );
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->month = arg2;
}


SWIGEXPORT short _wrap_TIMESTAMP_STRUCT_month_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::month", return 0);
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->month);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_day_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::day", return );
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->day = arg2;
}


SWIGEXPORT short _wrap_TIMESTAMP_STRUCT_day_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::day", return 0);
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->day);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_hour_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::hour", return );
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->hour = arg2;
}


SWIGEXPORT short _wrap_TIMESTAMP_STRUCT_hour_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::hour", return 0);
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->hour);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_minute_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::minute", return );
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->minute = arg2;
}


SWIGEXPORT short _wrap_TIMESTAMP_STRUCT_minute_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::minute", return 0);
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->minute);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_second_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::second", return );
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  arg2 = (SQLUSMALLINT)(*farg2);
  if (arg1) (arg1)->second = arg2;
}


SWIGEXPORT short _wrap_TIMESTAMP_STRUCT_second_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::second", return 0);
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  result = (SQLUSMALLINT) ((arg1)->second);
  fresult = (SQLUSMALLINT)(result);
  return fresult;
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_fraction_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::fraction", return );
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->fraction = arg2;
}


SWIGEXPORT int _wrap_TIMESTAMP_STRUCT_fraction_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagTIMESTAMP_STRUCT *", "TIMESTAMP_STRUCT", "tagTIMESTAMP_STRUCT::fraction", return 0);
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->fraction);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_TIMESTAMP_STRUCT() {
  SwigClassWrapper fresult ;
  struct tagTIMESTAMP_STRUCT *result = 0 ;
  
  result = (struct tagTIMESTAMP_STRUCT *)calloc(1, sizeof(struct tagTIMESTAMP_STRUCT));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_TIMESTAMP_STRUCT(SwigClassWrapper *farg1) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  
  arg1 = (struct tagTIMESTAMP_STRUCT *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_TIMESTAMP_STRUCT_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagTIMESTAMP_STRUCT *arg1 = (struct tagTIMESTAMP_STRUCT *) 0 ;
  struct tagTIMESTAMP_STRUCT *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_SQL_YEAR_MONTH_STRUCT_year_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_YEAR_MONTH *arg1 = (struct tagSQL_YEAR_MONTH *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_YEAR_MONTH *", "SQL_YEAR_MONTH_STRUCT", "tagSQL_YEAR_MONTH::year", return );
  arg1 = (struct tagSQL_YEAR_MONTH *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->year = arg2;
}


SWIGEXPORT int _wrap_SQL_YEAR_MONTH_STRUCT_year_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_YEAR_MONTH *arg1 = (struct tagSQL_YEAR_MONTH *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_YEAR_MONTH *", "SQL_YEAR_MONTH_STRUCT", "tagSQL_YEAR_MONTH::year", return 0);
  arg1 = (struct tagSQL_YEAR_MONTH *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->year);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_YEAR_MONTH_STRUCT_month_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_YEAR_MONTH *arg1 = (struct tagSQL_YEAR_MONTH *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_YEAR_MONTH *", "SQL_YEAR_MONTH_STRUCT", "tagSQL_YEAR_MONTH::month", return );
  arg1 = (struct tagSQL_YEAR_MONTH *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->month = arg2;
}


SWIGEXPORT int _wrap_SQL_YEAR_MONTH_STRUCT_month_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_YEAR_MONTH *arg1 = (struct tagSQL_YEAR_MONTH *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_YEAR_MONTH *", "SQL_YEAR_MONTH_STRUCT", "tagSQL_YEAR_MONTH::month", return 0);
  arg1 = (struct tagSQL_YEAR_MONTH *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->month);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_SQL_YEAR_MONTH_STRUCT() {
  SwigClassWrapper fresult ;
  struct tagSQL_YEAR_MONTH *result = 0 ;
  
  result = (struct tagSQL_YEAR_MONTH *)calloc(1, sizeof(struct tagSQL_YEAR_MONTH));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_SQL_YEAR_MONTH_STRUCT(SwigClassWrapper *farg1) {
  struct tagSQL_YEAR_MONTH *arg1 = (struct tagSQL_YEAR_MONTH *) 0 ;
  
  arg1 = (struct tagSQL_YEAR_MONTH *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_SQL_YEAR_MONTH_STRUCT_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagSQL_YEAR_MONTH *arg1 = (struct tagSQL_YEAR_MONTH *) 0 ;
  struct tagSQL_YEAR_MONTH *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_SQL_DAY_SECOND_STRUCT_day_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::day", return );
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->day = arg2;
}


SWIGEXPORT int _wrap_SQL_DAY_SECOND_STRUCT_day_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::day", return 0);
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->day);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_DAY_SECOND_STRUCT_hour_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::hour", return );
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->hour = arg2;
}


SWIGEXPORT int _wrap_SQL_DAY_SECOND_STRUCT_hour_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::hour", return 0);
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->hour);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_DAY_SECOND_STRUCT_minute_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::minute", return );
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->minute = arg2;
}


SWIGEXPORT int _wrap_SQL_DAY_SECOND_STRUCT_minute_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::minute", return 0);
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->minute);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_DAY_SECOND_STRUCT_second_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::second", return );
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->second = arg2;
}


SWIGEXPORT int _wrap_SQL_DAY_SECOND_STRUCT_second_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::second", return 0);
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->second);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_DAY_SECOND_STRUCT_fraction_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::fraction", return );
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  arg2 = (SQLUINTEGER)(*farg2);
  if (arg1) (arg1)->fraction = arg2;
}


SWIGEXPORT int _wrap_SQL_DAY_SECOND_STRUCT_fraction_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  SQLUINTEGER result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_DAY_SECOND *", "SQL_DAY_SECOND_STRUCT", "tagSQL_DAY_SECOND::fraction", return 0);
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  result = (SQLUINTEGER) ((arg1)->fraction);
  fresult = (SQLUINTEGER)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_SQL_DAY_SECOND_STRUCT() {
  SwigClassWrapper fresult ;
  struct tagSQL_DAY_SECOND *result = 0 ;
  
  result = (struct tagSQL_DAY_SECOND *)calloc(1, sizeof(struct tagSQL_DAY_SECOND));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_SQL_DAY_SECOND_STRUCT(SwigClassWrapper *farg1) {
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  
  arg1 = (struct tagSQL_DAY_SECOND *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_SQL_DAY_SECOND_STRUCT_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagSQL_DAY_SECOND *arg1 = (struct tagSQL_DAY_SECOND *) 0 ;
  struct tagSQL_DAY_SECOND *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_SQL_INTERVAL_STRUCT_interval_type_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQL_INTERVAL_STRUCT *arg1 = (struct tagSQL_INTERVAL_STRUCT *) 0 ;
  SQLINTERVAL arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_INTERVAL_STRUCT *", "SQL_INTERVAL_STRUCT", "tagSQL_INTERVAL_STRUCT::interval_type", return );
  arg1 = (struct tagSQL_INTERVAL_STRUCT *)farg1->cptr;
  arg2 = (SQLINTERVAL)(*farg2);
  if (arg1) (arg1)->interval_type = arg2;
}


SWIGEXPORT int _wrap_SQL_INTERVAL_STRUCT_interval_type_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQL_INTERVAL_STRUCT *arg1 = (struct tagSQL_INTERVAL_STRUCT *) 0 ;
  SQLINTERVAL result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_INTERVAL_STRUCT *", "SQL_INTERVAL_STRUCT", "tagSQL_INTERVAL_STRUCT::interval_type", return 0);
  arg1 = (struct tagSQL_INTERVAL_STRUCT *)farg1->cptr;
  result = (SQLINTERVAL) ((arg1)->interval_type);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_INTERVAL_STRUCT_interval_sign_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagSQL_INTERVAL_STRUCT *arg1 = (struct tagSQL_INTERVAL_STRUCT *) 0 ;
  SQLSMALLINT arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_INTERVAL_STRUCT *", "SQL_INTERVAL_STRUCT", "tagSQL_INTERVAL_STRUCT::interval_sign", return );
  arg1 = (struct tagSQL_INTERVAL_STRUCT *)farg1->cptr;
  arg2 = (SQLSMALLINT)(*farg2);
  if (arg1) (arg1)->interval_sign = arg2;
}


SWIGEXPORT short _wrap_SQL_INTERVAL_STRUCT_interval_sign_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagSQL_INTERVAL_STRUCT *arg1 = (struct tagSQL_INTERVAL_STRUCT *) 0 ;
  SQLSMALLINT result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_INTERVAL_STRUCT *", "SQL_INTERVAL_STRUCT", "tagSQL_INTERVAL_STRUCT::interval_sign", return 0);
  arg1 = (struct tagSQL_INTERVAL_STRUCT *)farg1->cptr;
  result = (SQLSMALLINT) ((arg1)->interval_sign);
  fresult = (SQLSMALLINT)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_SQL_INTERVAL_STRUCT_intval_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct tagSQL_INTERVAL_STRUCT *arg1 = (struct tagSQL_INTERVAL_STRUCT *) 0 ;
  tagSQL_INTERVAL_STRUCT_intval *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_INTERVAL_STRUCT *", "SQL_INTERVAL_STRUCT", "tagSQL_INTERVAL_STRUCT::intval", return SwigClassWrapper_uninitialized());
  arg1 = (struct tagSQL_INTERVAL_STRUCT *)farg1->cptr;
  result = (tagSQL_INTERVAL_STRUCT_intval *)& ((arg1)->intval);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_SQL_INTERVAL_STRUCT() {
  SwigClassWrapper fresult ;
  struct tagSQL_INTERVAL_STRUCT *result = 0 ;
  
  result = (struct tagSQL_INTERVAL_STRUCT *)calloc(1, sizeof(struct tagSQL_INTERVAL_STRUCT));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_SQL_INTERVAL_STRUCT(SwigClassWrapper *farg1) {
  struct tagSQL_INTERVAL_STRUCT *arg1 = (struct tagSQL_INTERVAL_STRUCT *) 0 ;
  
  arg1 = (struct tagSQL_INTERVAL_STRUCT *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_SQL_INTERVAL_STRUCT_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagSQL_INTERVAL_STRUCT *arg1 = (struct tagSQL_INTERVAL_STRUCT *) 0 ;
  struct tagSQL_INTERVAL_STRUCT *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_tagSQL_INTERVAL_STRUCT_intval_year_month_set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  tagSQL_INTERVAL_STRUCT_intval *arg1 = (tagSQL_INTERVAL_STRUCT_intval *) 0 ;
  SQL_YEAR_MONTH_STRUCT *arg2 = (SQL_YEAR_MONTH_STRUCT *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "tagSQL_INTERVAL_STRUCT_intval *", "tagSQL_INTERVAL_STRUCT_intval", "tagSQL_INTERVAL_STRUCT::tagSQL_INTERVAL_STRUCT_intval::year_month", return );
  arg1 = (tagSQL_INTERVAL_STRUCT_intval *)farg1->cptr;
  arg2 = (SQL_YEAR_MONTH_STRUCT *)farg2->cptr;
  if (arg1) (arg1)->year_month = *arg2;
}


SWIGEXPORT SwigClassWrapper _wrap_tagSQL_INTERVAL_STRUCT_intval_year_month_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  tagSQL_INTERVAL_STRUCT_intval *arg1 = (tagSQL_INTERVAL_STRUCT_intval *) 0 ;
  SQL_YEAR_MONTH_STRUCT *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "tagSQL_INTERVAL_STRUCT_intval *", "tagSQL_INTERVAL_STRUCT_intval", "tagSQL_INTERVAL_STRUCT::tagSQL_INTERVAL_STRUCT_intval::year_month", return SwigClassWrapper_uninitialized());
  arg1 = (tagSQL_INTERVAL_STRUCT_intval *)farg1->cptr;
  result = (SQL_YEAR_MONTH_STRUCT *)& ((arg1)->year_month);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_tagSQL_INTERVAL_STRUCT_intval_day_second_set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  tagSQL_INTERVAL_STRUCT_intval *arg1 = (tagSQL_INTERVAL_STRUCT_intval *) 0 ;
  SQL_DAY_SECOND_STRUCT *arg2 = (SQL_DAY_SECOND_STRUCT *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "tagSQL_INTERVAL_STRUCT_intval *", "tagSQL_INTERVAL_STRUCT_intval", "tagSQL_INTERVAL_STRUCT::tagSQL_INTERVAL_STRUCT_intval::day_second", return );
  arg1 = (tagSQL_INTERVAL_STRUCT_intval *)farg1->cptr;
  arg2 = (SQL_DAY_SECOND_STRUCT *)farg2->cptr;
  if (arg1) (arg1)->day_second = *arg2;
}


SWIGEXPORT SwigClassWrapper _wrap_tagSQL_INTERVAL_STRUCT_intval_day_second_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  tagSQL_INTERVAL_STRUCT_intval *arg1 = (tagSQL_INTERVAL_STRUCT_intval *) 0 ;
  SQL_DAY_SECOND_STRUCT *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "tagSQL_INTERVAL_STRUCT_intval *", "tagSQL_INTERVAL_STRUCT_intval", "tagSQL_INTERVAL_STRUCT::tagSQL_INTERVAL_STRUCT_intval::day_second", return SwigClassWrapper_uninitialized());
  arg1 = (tagSQL_INTERVAL_STRUCT_intval *)farg1->cptr;
  result = (SQL_DAY_SECOND_STRUCT *)& ((arg1)->day_second);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_tagSQL_INTERVAL_STRUCT_intval() {
  SwigClassWrapper fresult ;
  tagSQL_INTERVAL_STRUCT_intval *result = 0 ;
  
  result = (tagSQL_INTERVAL_STRUCT_intval *)calloc(1, sizeof(tagSQL_INTERVAL_STRUCT_intval));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_tagSQL_INTERVAL_STRUCT_intval(SwigClassWrapper *farg1) {
  tagSQL_INTERVAL_STRUCT_intval *arg1 = (tagSQL_INTERVAL_STRUCT_intval *) 0 ;
  
  arg1 = (tagSQL_INTERVAL_STRUCT_intval *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_tagSQL_INTERVAL_STRUCT_intval_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  tagSQL_INTERVAL_STRUCT_intval *arg1 = (tagSQL_INTERVAL_STRUCT_intval *) 0 ;
  tagSQL_INTERVAL_STRUCT_intval *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT SwigArrayWrapper _wrap_ODBCINT64_TYPE_get() {
  SwigArrayWrapper fresult ;
  char *result = 0 ;
  
  result = (char *)("long");
  fresult.size = strlen((char*)(result));
  fresult.data = (char *)(result);
  return fresult;
}


SWIGEXPORT SwigArrayWrapper _wrap_UODBCINT64_TYPE_get() {
  SwigArrayWrapper fresult ;
  char *result = 0 ;
  
  result = (char *)("unsigned long");
  fresult.size = strlen((char*)(result));
  fresult.data = (char *)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SQL_MAX_NUMERIC_LEN_get() {
  int fresult ;
  int result;
  
  result = (int)(16);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_NUMERIC_STRUCT_precision_set(SwigClassWrapper *farg1, signed char const *farg2) {
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLCHAR arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::precision", return );
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  arg2 = (SQLCHAR)(*farg2);
  if (arg1) (arg1)->precision = arg2;
}


SWIGEXPORT signed char _wrap_SQL_NUMERIC_STRUCT_precision_get(SwigClassWrapper *farg1) {
  signed char fresult ;
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLCHAR result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::precision", return 0);
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  result = (SQLCHAR) ((arg1)->precision);
  fresult = (SQLCHAR)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_NUMERIC_STRUCT_scale_set(SwigClassWrapper *farg1, signed char const *farg2) {
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLSCHAR arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::scale", return );
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  arg2 = (SQLSCHAR)(*farg2);
  if (arg1) (arg1)->scale = arg2;
}


SWIGEXPORT signed char _wrap_SQL_NUMERIC_STRUCT_scale_get(SwigClassWrapper *farg1) {
  signed char fresult ;
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLSCHAR result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::scale", return 0);
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  result = (SQLSCHAR) ((arg1)->scale);
  fresult = (SQLSCHAR)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_NUMERIC_STRUCT_sign_set(SwigClassWrapper *farg1, signed char const *farg2) {
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLCHAR arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::sign", return );
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  arg2 = (SQLCHAR)(*farg2);
  if (arg1) (arg1)->sign = arg2;
}


SWIGEXPORT signed char _wrap_SQL_NUMERIC_STRUCT_sign_get(SwigClassWrapper *farg1) {
  signed char fresult ;
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLCHAR result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::sign", return 0);
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  result = (SQLCHAR) ((arg1)->sign);
  fresult = (SQLCHAR)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQL_NUMERIC_STRUCT_val_set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLCHAR *arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::val", return );
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  arg2 = (SQLCHAR *)farg2->cptr;
  {
    size_t ii;
    SQLCHAR *b = (SQLCHAR *) arg1->val;
    for (ii = 0; ii < (size_t)16; ii++) b[ii] = *((SQLCHAR *) arg2 + ii);
  }
}


SWIGEXPORT SwigClassWrapper _wrap_SQL_NUMERIC_STRUCT_val_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  SQLCHAR *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQL_NUMERIC_STRUCT *", "SQL_NUMERIC_STRUCT", "tagSQL_NUMERIC_STRUCT::val", return SwigClassWrapper_uninitialized());
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  result = (SQLCHAR *)(SQLCHAR *) ((arg1)->val);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_SQL_NUMERIC_STRUCT() {
  SwigClassWrapper fresult ;
  struct tagSQL_NUMERIC_STRUCT *result = 0 ;
  
  result = (struct tagSQL_NUMERIC_STRUCT *)calloc(1, sizeof(struct tagSQL_NUMERIC_STRUCT));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_SQL_NUMERIC_STRUCT(SwigClassWrapper *farg1) {
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  
  arg1 = (struct tagSQL_NUMERIC_STRUCT *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_SQL_NUMERIC_STRUCT_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagSQL_NUMERIC_STRUCT *arg1 = (struct tagSQL_NUMERIC_STRUCT *) 0 ;
  struct tagSQL_NUMERIC_STRUCT *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_SQLGUID_Data1_set(SwigClassWrapper *farg1, int const *farg2) {
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  DWORD arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data1", return );
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  arg2 = (DWORD)(*farg2);
  if (arg1) (arg1)->Data1 = arg2;
}


SWIGEXPORT int _wrap_SQLGUID_Data1_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  DWORD result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data1", return 0);
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  result = (DWORD) ((arg1)->Data1);
  fresult = (DWORD)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQLGUID_Data2_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  WORD arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data2", return );
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  arg2 = (WORD)(*farg2);
  if (arg1) (arg1)->Data2 = arg2;
}


SWIGEXPORT short _wrap_SQLGUID_Data2_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  WORD result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data2", return 0);
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  result = (WORD) ((arg1)->Data2);
  fresult = (WORD)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQLGUID_Data3_set(SwigClassWrapper *farg1, short const *farg2) {
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  WORD arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data3", return );
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  arg2 = (WORD)(*farg2);
  if (arg1) (arg1)->Data3 = arg2;
}


SWIGEXPORT short _wrap_SQLGUID_Data3_get(SwigClassWrapper *farg1) {
  short fresult ;
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  WORD result;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data3", return 0);
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  result = (WORD) ((arg1)->Data3);
  fresult = (WORD)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SQLGUID_Data4_set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  BYTE *arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data4", return );
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  arg2 = (BYTE *)farg2->cptr;
  {
    size_t ii;
    BYTE *b = (BYTE *) arg1->Data4;
    for (ii = 0; ii < (size_t)8; ii++) b[ii] = *((BYTE *) arg2 + ii);
  }
}


SWIGEXPORT SwigClassWrapper _wrap_SQLGUID_Data4_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  BYTE *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct tagSQLGUID *", "SQLGUID", "tagSQLGUID::Data4", return SwigClassWrapper_uninitialized());
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  result = (BYTE *)(BYTE *) ((arg1)->Data4);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_SQLGUID() {
  SwigClassWrapper fresult ;
  struct tagSQLGUID *result = 0 ;
  
  result = (struct tagSQLGUID *)calloc(1, sizeof(struct tagSQLGUID));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_SQLGUID(SwigClassWrapper *farg1) {
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  
  arg1 = (struct tagSQLGUID *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_SQLGUID_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct tagSQLGUID *arg1 = (struct tagSQLGUID *) 0 ;
  struct tagSQLGUID *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}



